### ISSUE TITLE
Partial lack of cubic source files

### ISSUE THREAD

**Issue by adrientetar** [RedHatBrand/overpass#1]
In the source files presented here, only the light weight has Postscript curves which are what's used to draw.

So a complete open-source release of these fonts which allows designers to contribute or create derivatives would involve complete release of cubic font source files (conversion from TTF to Postscript is notably lossy).

By the way: proprietary VFB files can now be converted to open-source UFOs using the [vfb2ufo](http://blog.fontlab.com/font-utility/vfb2ufo/) utility &ndash; it is seegmingly [still botchy](https://twitter.com/adrientetar/status/584698823877996544) as I experienced when trying to convert the Overpass fonts, but it can be valuable eventually to have UFOs alongside VFBs in the repo (esp. since vfb2ufo only runs on Windows and Macintosh, just like FontLab itself).

**Comment by adrientetar** [comment]
Also it seems the files with quadratic curves (tagged as v1.001) have slightly different metrics, e.g. the baseline overshoot is -20 0 instead of -12 0.

**Comment by andyfitz** [comment]
This is excellent feedback.   
We're preparing italics and an extra light before the formal release of this font family so identifying these issues now helps a great deal before we finish the initial set.

I'm a fontforge user myself but Delve prefers Fontlab - after completion we should probably migrate to UFO.

**Comment by andyfitz** [comment]
Also worth noting that Regular and Bold were designed around freetype for software/screen only.  Light had a wider scope.  Hopefully we can circle back and standardise Regular and Bold

**Comment by andyfitz** [comment]
Happy to take any pull requests of your migration efforts BTW.  Thanks very much for your interest.

**Comment by adrientetar** [comment]
> Happy to take any pull requests of your migration efforts BTW. Thanks very much for your interest.

For now there is this vfb2ufo bug but it should be done around final release I think.

Also some feedback on the Light master: acute and grave seem off. Here's my name written with it (no kerning due to the vfb2ufo bug):

![opass1v](https://cloud.githubusercontent.com/assets/1250894/6996976/3bab40be-dba8-11e4-85ae-194ca84e599b.png)

The acute is slipping off of the letter.

![opass](https://cloud.githubusercontent.com/assets/1250894/6996978/59bf5770-dba8-11e4-8af9-0092fc90c4a1.PNG)

With a quick fix it looks already better:

![overpass3](https://cloud.githubusercontent.com/assets/1250894/6996999/899c05b4-dba9-11e4-991e-9c9070f5e88b.PNG)

SVG code:

~~~
<?xml version="1.0" standalone="no"?>
<!DOCTYPE svg PUBLIC "-//W3C//DTD SVG 1.1//EN" "http://www.w3.org/Graphics/SVG/1.1/DTD/svg11.dtd" >
<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" version="1.1" viewBox="0 -200 1000 1000">
  <g transform="matrix(1 0 0 -1 0 800)">
   <path fill="currentColor"
d="M462 227c2 22 2 38 2 49c0 172 -93 247 -202 247c-131 0 -222 -97 -222 -267c0 -144 84 -268 222 -268c59 0 116 25 156 58l-38 47c-39 -29 -78 -40 -115 -40c-87 0 -139 70 -151 174h348zM262 460c54 0 130 -32 131 -170h-281c6 116 68 170 150 170zM413 732h-109
l-110 -156h65z" />
  </g>
</svg>
~~~

Also I notice cimcumflex and tilde feel too constructed for the design of Overpass, and tilde seem like it has too much contrast variation.

If I may suggest two great resources for diacritics design (which, tbh, is an unexpectedly uneasy part of the design process):

- [Problems of diacritics design for latin script text faces](http://typefacedesign.net/wp-content/uploads/2013/08/MATD01_VG_ProbDiacLo.pdf) &ndash; by Victor J. Gaultney
- [The diacritics project](http://diacritics.typo.cz/) at typo.cz
