### ISSUE TITLE
Missing glyphs in IE9

### ISSUE THREAD

**Issue by lekkerduidelijk** [RedHatBrand/Overpass#10]
Some glyphs seem to be missing in the Overpass Bold EOT file.

![missing-letters-ie9-win7](https://cloud.githubusercontent.com/assets/357924/10279531/cb2e0bce-6b66-11e5-87fd-3e63f26086ee.png)

So far I've found these: A Y V X

Could you please build that font variant again?

**Comment by andyfitz** [comment]
This is a weird one.   unfortunately I don’t test on IE9.
Does this affect Microsoft's rebranded IE ?   Edge or whatever it's called?
Because if not,  I'd rather expire EOT as a deprecated format than support and maintain files we can't test.

**Comment by andyfitz** [comment]
@DelveFonts  what do you reckon ?

**Comment by lekkerduidelijk** [comment]
I can confirm it only has issues on IE9. IE10 and above look fine. In the network inspector I see IE9 and IE10 both do use the same .eot files.

![IE9 and IE10 side by side](https://cloud.githubusercontent.com/assets/357924/10428699/8c84ab48-70f3-11e5-8dc8-a959120b2d2d.png)

On [Stackoverflow](http://stackoverflow.com/questions/8429654/font-face-missing-characters-glyphs-in-ie9) I read it could have something todo with a "corruption in the conversion that IE can't handle".

I thought maybe a rebuild could fix this.

**Comment by DelveFonts** [comment]
Thanks @lekkerduidelijk for bringing this to our attention. @andyfitz Edge does not support EOT. AFAIK, EOT's are only used by IE 8-11 with an estimated collective support globally at < 10%*.

_*Source: http://caniuse.com/#search=eot_

**Comment by andyfitz** [comment]
Version 3.0 has been released and while the site still needs to be updated,  I think this issue has been resolved.
