### ISSUE TITLE
Remove RFN

### ISSUE THREAD

**Issue by davelab6** [RedHatBrand/overpass#12]
I'm curious why in https://github.com/RedHatBrand/overpass/blob/master/LICENSE.md the "Reserved Font Name" option was chosen?

I suggest removing it: Since Overpass is a trademark of Red Hat then it is not necessary; and it limits use of the font as a web font because format changes (EOT/WOFF) and sub-setting are defined as modification in the OFL and so if I want to self-host the fonts and subset them myself, either I have to rename the fonts, or I have to contact Red Hat and get additional permission granted (which is costly.) 

Additionally the RFN means that the Github fork/modify/pull-request/merge process becomes Github fork/rename/modify/manual-pull-request/re-rename/merge which isn't ideal. 

To remove the RFN, in each copyright statement change from

> Copyright 2015 Red Hat, Inc., with Reserved Font Name OVERPASS.

to 

> Copyright 2015 Red Hat, Inc.

**Comment by andyfitz** [comment]
Resolved :)
