### ISSUE TITLE
Overpass font weights & Microsoft Office

### ISSUE THREAD

**Issue by nicoconstanzo** [RedHatBrand/overpass#15]
I have downloaded and installed the whole family of desktop fonts for usage with  Office (notably Word and Powerpoint).

The problem I am having is that Office doesn't easily support multiple font weights. This means it uses the Regular version by default, which is already more of a bold in itself and no option to choose the "Light" version which is better suited for body copy. 

I have tried:
- make Windows take each font as a "family" of it's own (i.e: Overpass Light, Overpass Regular, etc.) but I couldn't get it to work. It might require editing the files themselves but I'm not sure where. 
- specifically selecting the "Light" version in advanced settings in Word but it keeps going back to regular.

Do you have any workarounds or tips to solve this? I would love to be able to use this font on my documents!

Thanks!

**Comment by andyfitz** [comment]
This is a known issue.  unfortunately Overpass inherited this issue from back when it was only regular and bold.  (almost everyone uses light as their default weight).

I'm not sure how to fix this other than through a major release with a new weight classification.  
Things could get messy for people upgrading so it might depend on changing the font family name entirely...     

Thinking about what to do but don't expect a fix anytime soon sadly.

**Comment by nicoconstanzo** [comment]
Hi! Thanks for your reply. Yes, here we've been using the Light version as the default weight which looks a lot nicer for body text. 

What I finally did was edit the font name directly with TransType 4 (which has a free trial), making the Overpass-light be the regular weight and the regular be the bold. It's a bit of a workaround but it's worked fine.

It's a beautiful font, keep up the good work. Cheers!

**Comment by andyfitz** [comment]
I'm going to close this issue since it probably wont be fixed without a name change.   
But yeah, I wish we started with a _real_ regular weight
