### ISSUE TITLE
Any plan for new minor release with Hinting support?

### ISSUE THREAD

**Issue by pravins** [RedHatBrand/overpass#17]
Hi,
   Any plan to do minor release with hinting information added by commit: https://github.com/RedHatBrand/overpass/commit/4458bf24ee2365b539a11eff529ae860246abfc8

   Want to update this font in Fedora. Minor release will be very helpful.

**Comment by pravins** [comment]
ping.. :)

**Comment by andyfitz** [comment]
Hey I'm on paternity. Cleaning diapers .. I'll make the release in early Dec :-)

**Comment by pravins** [comment]
No problem. Rather than packaging based on commit i think we can wait for release.
Have a good time. :)

**Comment by pravins** [comment]
Gentle reminder :)

**Comment by andyfitz** [comment]
hi @pravins I'm drowning under a few other tasks right now.
So.. this means you are now the minor release maintainer of Overpass
congratulations be gentle  (and thank you for your Fedora contributions )  ;-)

**Comment by pravins** [comment]
Thanks for permission :)
I gone through git and earlier release structure. New release tarball available At https://pravins.fedorapeople.org/overpass-fonts/

Please note, i have created Makefile,  https://pravins.fedorapeople.org/overpass-fonts/Makefile
This will be useful for next releases. Just update version in this file and say Make all. :)

With each update we should change version inside font, present release and 
2.0 release has font verion : 1.001
2.1 release we are doing now.: "Version 1.001; ttfautohint (v1.3)"

I think good, if we can keep internal font version matching with our release version :)
Can you push these files to download section now. I dont have access for it.

**Comment by pravins** [comment]
Built test rpm with updated zip: 
https://pravins.fedorapeople.org/overpass-fonts/overpass-fonts-2.1-1.fc23.noarch.rpm

Source rpm
https://pravins.fedorapeople.org/overpass-fonts/overpass-fonts-2.1-1.fc23.src.rpm

Waiting for uploading these file zip file to git download place.

**Comment by andyfitz** [comment]
Thank you, thankyoum thank you @pravins 

You're an admin on the repo now also :) :+1:

**Comment by pravins** [comment]
Great, thanks a lot :)
Will follow closely and surely help wherever possible !!

**Comment by andyfitz** [comment]
https://github.com/RedHatBrand/overpass/releases/tag/2.1   all done

**Comment by pravins** [comment]
Thank you @andyfitz  :+1:
