### ISSUE TITLE
Webfont Files Download button leads to wrong package

### ISSUE THREAD

**Issue by JaniKarh** [RedHatBrand/overpass#21]
The download link (https://github.com/RedHatBrand/overpass/releases/download/2.1/overpass-fonts-web-fonts-2.1.zip) on http://overpassfont.org/ leads to a package with the same content as Desktop bundle.

Should include svg, woff, etc. I believe?

**Comment by andyfitz** [comment]
Right you are!  
Sorry about that!
Today I'm removing the button since a new release is pending and we can fix the link then.
