### ISSUE TITLE
some woff-Files seem to be corrupt in ZIP

### ISSUE THREAD

**Issue by DerExilant** [RedHatBrand/Overpass#22]
I've used the woff files from the webfonts zip and the files Overpass-Regular.woff and Overpass-Light.woff where reported as undecodeable by chrome. I've got these files from the overpass-font-web-fonts-2.1.zip. The files I've downloaded from the code section work fine.

**Comment by andyfitz** [comment]
Thanks for the heads up. 
This should be fixed in the next release from @DelveFonts ,  for now I've removed the package link

**Comment by keripix** [comment]
I also faced the problem ini Firefox 43, but only for the Overpass-Light.woff

**Comment by andyfitz** [comment]
All new woff files in V3,  none of them seem to be corrupt :)
