### ISSUE TITLE
Any plans to release a monospace / fixed width variation?

### ISSUE THREAD

**Issue by gavinlaking** [RedHatBrand/overpass#23]
Nice font! Is there any plans to release a monospace/fixed width variation suitable for programming?

**Comment by aleksandar-todorovic** [comment]
I believe that this has been confirmed [here](https://github.com/RedHatBrand/overpass/issues/14#issuecomment-169360812). Can't wait to see the mono version!

**Comment by andyfitz** [comment]
Yes that's on the queue and the initial regular and bold monospace variants should make debut soon
