### ISSUE TITLE
Font-weights 200 & 400 are identical

### ISSUE THREAD

**Issue by thany** [RedHatBrand/overpass#24]
On overpassfont.org the font-weights 200 and 400 are completely identical. Is there a reason to have that choice then? It might be better to remove one of them, I'd say. Or if there's supposed to be a difference, make sure it shows.

Also, some of the glyphs show a rectangle with a hex number in it for 200 & 400, but for 600.

**Comment by andyfitz** [comment]
They aren't identical  maybe your browser didnt load them yet ?

**Comment by thany** [comment]
I tried a couple of times, but the browser was definitely done loading. No progress indication anywhere, but I guess I could check the network log (when I get to a computer again)

**Comment by andyfitz** [comment]
![400-200-visible-weights](https://cloud.githubusercontent.com/assets/1276715/12739189/2bcf9f3a-c9a2-11e5-849f-0196b7c15d48.gif)

**Comment by thany** [comment]
I appreciate you making the animation showing the problem doesn't happen for you... But it does for me. I always say, if I have this problem, others might as well...

**Comment by andyfitz** [comment]
There's about to be a major update to all files so hopefully this fixes the issue .  I'll keep it open for now.  thanks for raising it :+1:
