### ISSUE TITLE
Different heights between 200/400 and 600/700 weights

### ISSUE THREAD

**Issue by yuchi** [RedHatBrand/Overpass#25]
In the online preview of the Web Font is possible to notice a difference in heights between different weights. In the next image I tried to highlight the difference by placing a box just under the last pixel of straight letters (lower case `H` and upper case `I`). You can see the purple box (for `200` and `400`) overlaps vertically only part of the blue box (`600` and `700`).

<img width="304" alt="Overpass weights’ heights comparison" src="https://cloud.githubusercontent.com/assets/646609/12750024/89aae3c8-c9b4-11e5-8f54-1064bd5001b8.png">

Also if an inline element breaks this barrier (such as a `<strong>` inside text with the `400` weight) it changes the height of the line. In the next image I highlighted the endings of the bottom separator line between the ‘normal’ case and the case with a bolder word.

<img width="312" alt="Inline weights comparison" src="https://cloud.githubusercontent.com/assets/646609/12750340/dc3497f4-c9b6-11e5-999f-e4fad1b4b466.png">

I tested that this issue is reproducible in the following cases:
- inner inline `600` inside `400` block;
- inner inline `700` inside `400` block;
- inner inline `600` inside `200` block;
- inner inline `700` inside `200` block.

It is **also** reproducible in the following cases:
- inner inline `200` inside `600` block;
- inner inline `400` inside `600` block;
- inner inline `200` inside `700` block;
- inner inline `400` inside `700` block;

It is **not** reproducible in these:
- inner inline `600` inside `700` block;
- inner inline `700` inside `600` block;
- inner inline `200` inside `400` block;
- inner inline `400` inside `200` block;

---

I initially thought it was something related to some issues in hinting heavier weights. The fact that there are issues rendering **lighter** weights inside heavier ones made me change my mind.

I can only infer it is still something related to hinting, but probably the vertical position of characters are to be blamed for this strange behavior.

I didn’t have time to understand if this is an issue limited to the Web Font, which I reproduced the issues with, or more generally with the font design.
I’m also completely unaware of how to diagnose if the origin has to be found in the fonts.

---

Thank you for a great typeface design and font execution.

**Comment by DelveFonts** [comment]
Thank you @yuchi for pointing this issue out. It will be resolved with the next update.

**Comment by yuchi** [comment]
Would you mind to reference this issue in commits so that I can follow the changes? While completely ignorant in design and pratical issues around font face implementation, I’m very willing to learn.

**Comment by DelveFonts** [comment]
Will do.

**Comment by andyfitz** [comment]
the metrics have been resolved thanks to the new 3.0 release.

Thanks for your patience!

**Comment by yuchi** [comment]
@andyfitz Could you please give me some details on how that happened and you solved it?
