### ISSUE TITLE
Why dual-licensed under LGPL 2.1?

### ISSUE THREAD

**Issue by richardfontana** [RedHatBrand/overpass#28]
Overpass fonts were originally intended to be licensed under the SIL OFL 1.1. As of https://github.com/RedHatBrand/overpass/commit/0d2d650bddfe50f3f1f595cb6e3e2562ec837830 it said to be dual-licensed under LGPL 2.1. What was the reason for this license change? LGPL seems unsuitable as a license for fonts.

**Comment by davelab6** [comment]
I agree that LGPL is unsuitable for fonts. 

I believe that the first Ubuntu font that @andyfitz designed was released under the LGPL, before the OFL became widely known if not predating it; and there are a few other LGPL fonts floating around, but generally the "Go OFL!" campaign has upgraded them to OFL over the years.

**Comment by andyfitz** [comment]
For better or worse, LGPL is _the_ 'no brainer license' for developers looking to embed fonts in their software without major copyleft concerns.  

OFL has an awareness problem for non font savvy developers in this regard and we didn't want roadblocks in the way of adoption.
OFL is of course the preference, but there's not much recourse from supporting LGPL also and that's why we did.

**Comment by davelab6** [comment]
But OFL says "only this license" so downstream users may get into trouble

**Comment by richardfontana** [comment]
@andyfitz okay no objection assuming (as seems to be the case) there is no legal obstacle to the additional license choice. At least it is not the Liberation Fonts license (to which the choice of OFL for Overpass can be seen as a strong reaction). 

@davelab6 I am not concerned about the "only this license" issue since the copyright owner can dual-license under OFL or another license.

**Comment by davelab6** [comment]
> I am not concerned about the "only this license" issue since the copyright owner can dual-license under OFL or another license.

What do downstream users do?

**Comment by richardfontana** [comment]
@davelab6 downstream users can pass on the choice or explicitly pick one or the other license (here OFL or LGPL).

**Comment by andyfitz** [comment]
Thanks for the excellent advice @richardfontana
