### ISSUE TITLE
Add license metadata to all fonts

### ISSUE THREAD

**Issue by christopheradams** [RedHatBrand/Overpass#3]
Most of the TTF files seem to be missing the license metadata. Only `Overpass_Bold.ttf` and `Overpass_Regular.ttf` have it, the rest don't.

```
$ fontaine overpass/Desktop\ Fonts/Overpass\ Bold\ Italic.ttf | grep license
"license":"Unknown or Proprietary License",
```

I'd also suggest dropping a copy of the license into the ZIP file.

**Comment by DelveFonts** [comment]
Good catch! Thanks Christopher. This will be addressed in the next update.

**Comment by andyfitz** [comment]
All fixed
