### ISSUE TITLE
Add latex package

### ISSUE THREAD

**Issue by Fale** [RedHatBrand/Overpass#30]
A think it would be nice to have a latex package to be able to use in an easy way the overpass font in latex

**Comment by andyfitz** [comment]
hrmmm..  this sound good but outside of my realm.  Please send a pull-request if you can.

**Comment by buuhsmead** [comment]
With help of this page I was able to use the Overpass font(s).
http://tex.stackexchange.com/questions/46/how-do-i-use-an-opentype-font-with-my-latex-document.
I do have the fonts installed as system font. 

\usepackage{xltxtra}
\setmainfont{Overpass Regular}

**Comment by Fale** [comment]
Yes, XeTeX supports such fonts, but brings with it many consequences
