### ISSUE TITLE
Increase difference between letters 'l', 'I'

### ISSUE THREAD

**Issue by jarlarntzen** [RedHatBrand/Overpass#31]
**Il** (`Il`)
I would like to suggest adding slight differences in height for the letters `I` and `l` as well as a slight lower serif for the `l` in order to make them better distinguishable.

**Comment by jarlarntzen** [comment]
Actually, I see now that there actually is a difference but it is very slight and I failed to see it at 14pt size.

**Comment by andyfitz** [comment]
the monospace files in v3 have deliberate differences between glyphs whereas the proportional is deliberately homogenous for some of those forms for cosmetic reasons.
