### ISSUE TITLE
space & nbspace do not have the same width

### ISSUE THREAD

**Issue by m4rc1e** [RedHatBrand/Overpass#32]
Hey folks,

The space uni0020 should have the same horizontal metrics as nbspace uni00A0.

![screen shot 2016-11-18 at 12 43 56](https://cloud.githubusercontent.com/assets/7525512/20429074/b6495e8e-ad8c-11e6-83f1-bd7492a6f523.png)

I found this error in the Thin and Light. 

My [Glyphsapp scripts](https://github.com/m4rc1e/mf-glyphs-scripts) has QA scripts to check these issues.

**Comment by davelab6** [comment]
This is required for Google Docs text to work correctly

**Comment by DelveFonts** [comment]
Thank you for bringing this to our attention @m4rc1e. This will be corrected in a minor bug-fix update currently in the works here. @davelab6 Does Google Docs make use of any other whitespace characters?

**Comment by davelab6** [comment]
Not afaik. You can now easily check fonts to gf requirements with
fontbakery.appspot.com thanks to hard work by @felipesanches

**Comment by DelveFonts** [comment]
Ok, thanks Dave.

**Comment by DelveFonts** [comment]
Fixed! Corrected files are in Overpass version 3.01 and Overpass Mono version 1.01 coming your way very soon.

**Comment by m4rc1e** [comment]
Thank you sir
