### ISSUE TITLE
Win metrics causing clipping

### ISSUE THREAD

**Issue by m4rc1e** [RedHatBrand/Overpass#33]
Hey,

The Win Metrics are causing clipping in Window's applications. The [spec](https://www.microsoft.com/typography/OTSpec/os2.htm#wa) is a rather interesting read for these values. At GF it is policy to make the win Ascent and win Descent the ymin, ymax of the font's bbox. I've peiced together a quick glyphsapp [script](https://gist.github.com/m4rc1e/731d4a5f3b5b3425edcb4bfcae80302e) to report the ymin, ymax in Glyphsapp for a source file.

![screen shot 2016-11-18 at 13 08 50](https://cloud.githubusercontent.com/assets/7525512/20429665/5dffc30e-ad90-11e6-97e7-c6d01865de65.png)

Remember that radically changing these values may upset users and cause their documents to overflow. I can write more on this soonish.

Cheers,
Marc

**Comment by davelab6** [comment]
I suggest making the change even if it is disruptive for users because clipping or cutting off essential parts of the letters is never going to get better for readers of those glyphs, but a little reflow can be worked around 😄

**Comment by DelveFonts** [comment]
Thank you @m4rc1e for pointing this out and @davelab6 for weighing in. We will review and determine the appropriate revisions to make for this.

**Comment by andyfitz** [comment]
I'm okay for reflow also;  almost all of our uses are purely as webfonts with pretty robust layout rules.

**Comment by DelveFonts** [comment]
Fixed! New versions are on the way.
