### ISSUE TITLE
Add support for Powerline symbols

### ISSUE THREAD

**Issue by nertpinx** [RedHatBrand/Overpass#34]
When trying Overpass Mono in terminal with powerline symbols, it works only if I select Light version of the font. Any other version is missing the symbols.  Here are two example symbols that show exactly this behaviour:  

If you let me know how to debug it further or work with the glyph files (I couldn't find any way to edit them and build the font files), I'd be happy to help with this.

**Comment by davelab6** [comment]
Perhaps as a quick fix the glyphs in the light can be copied to the glyphs in the other styles, then when other versions of other weights for the glyphs become available they can be used?

**Comment by nertpinx** [comment]
I would like to try that, but I'm not sure how to build the OTF from the glyphs, nor how to edit the glyphs file. Any hints appreciated.

**Comment by DelveFonts** [comment]
@nertpinx We are not familiar with those glyph names. Please provide the unicode positions to clarify which characters those are.

**Comment by nertpinx** [comment]
Oh, I'm sorry. It's from the PUA. I haven't realized that these particular code points are intentionally standardized (see "Powerline" in https://en.wikipedia.org/wiki/Private_Use_Areas ). I am still wondering, though, how come it is in the Light font and not in any other?

**Comment by DelveFonts** [comment]
Ah, thanks for the clarification @nertpinx. The Powerline glyphs are actually not in the Light (or any weight) of Overpass. I suspect the glyphs you are seeing may be displayed in another (fall-back) font. However, the Powerline glyphs would be good additions to Overpass Mono, so we will put them on the list for an update.

**Comment by nertpinx** [comment]
I would expect the fallback to happen either for all fonts or no font at all. Anyway, I'm glad you feel that would be valuable. Thank you very much for considering that.

**Comment by andyfitz** [comment]
the powerline symbols work fine for me (falling back to other fonts)
![screenshot from 2016-11-28 10-52-01](https://cloud.githubusercontent.com/assets/1276715/20653395/b71653ac-b558-11e6-883c-e3113e8eca10.png)

**Comment by nertpinx** [comment]
Is that true for both Light and Regular variants? It works for me with the Light variant, but doesn't with any other one. I tried tweaking the configuration and still Light differs from others (for both Mono and normal). It may be misconfiguration on my side, but I think that either all or none would work in that case.

**Comment by andyfitz** [comment]
mono light semibold and bold work for me  but regular fails -     this has more to do with out systems trying to do glyph based fallback at matching properties than it does about the font.   maybe I have fallback weights in all but regular

**Comment by nertpinx** [comment]
Yes, it looks like my fontconfig settings are messed up. Sorry for taking your time.
