### ISSUE TITLE
subscripts char !

### ISSUE THREAD

**Issue by HamzaTalaghzi** [RedHatBrand/Overpass#36]
subscripts char is bigger than what is supposed to be and its font-weight is much bold compared to others char
you can try this to see difference : 123456789abcx₁₂₃₄₅₆₇₈₉₀

**Comment by DelveFonts** [comment]
@HamzaTalaghzi To be clear, are you referring to the subscripts in the Monospace set or the normal (proportional) family?

**Comment by HamzaTalaghzi** [comment]
I'm actually using the normal web-font and to be honest i'm not expert in that domain 
I'm just didn't like the look of this subscripts but in general the font is very beautiful ;
Nice work 👍
