### ISSUE TITLE
vertical metrics on v3.001

### ISSUE THREAD

**Issue by m4rc1e** [RedHatBrand/Overpass#37]
Hey folks,

Sorry to disturb again. Ok, you've solved the clipping but the line spacing is now too loose. Since it's a Friday, I'll take a stab at this myself I think. Give me a few hours.

![screen shot 2016-12-02 at 13 48 46](https://cloud.githubusercontent.com/assets/7525512/20834566/6faf93e8-b896-11e6-8a5f-aca12826a543.png)
![screen shot 2016-12-02 at 13 48 18](https://cloud.githubusercontent.com/assets/7525512/20834567/701c3df4-b896-11e6-9c94-3043d94dbfbf.png)

There is a flag in the OS/2 table called, 'Use_Typo_Metrics'. Enabling this flag will make Window's applications use the OS/2 typo asc and typo desc values, instead of the Win Asc and Win Desc. Using this flag is crucial in solving this problem. By not enabling this flag and changing the win asc and desc to the bbox, we get this problem.

This error is especially troublesome on the Monospace fonts because Sublime, Notepad, vim etc all don't have control over line-height/leading.

Cheers,
Marc

**Comment by m4rc1e** [comment]
Just gathering more info, I could end up with egg on my face here

**Comment by m4rc1e** [comment]
I've compared the metrics against the old fonts and figured out values which should retain the old leading and not lead to clipping. 

We currently have this situation:

**Left: Old Right: New**
![screen shot 2016-12-02 at 14 55 59](https://cloud.githubusercontent.com/assets/7525512/20836434/7da252a2-b89f-11e6-887a-c9ae969f6f14.png)


old value totals:
win total = 1266
typo total = 1266
hhea total = 1266

new value totals:
win total = 1440
typototal = 1266
hheatotal = 1440

Proposed value totals:
win total = 1440
typo total = 1266
hhea total = 1266
*Enable use typo metrics flag in OS/2 table*

Basically, my proposed typo and hhea values are the same as the old.  We adopt the new win asc and desc. To negate the consequences of the larger spacing caused by the new win values, we enable '[use typo metrics](https://www.microsoft.com/typography/OTSpec/os2.htm#fss)'. By doing this, we get the following

**Left: Proposed, MIddle: Old, Right:New**
![screen shot 2016-12-02 at 14 54 07](https://cloud.githubusercontent.com/assets/7525512/20836600/65096bf8-b8a0-11e6-8734-3eb947e4d0b0.png)

Here's the proposed vertical metric values

```
typoAscender: 750
typoDescender: -250
typoLineGap: 266

hheaAscender: 982
hheaDescender: -284

winAscent: 1062
winDescent: 378

```
To enable Use Typo Metrics in glyphsapp:
![screen shot 2016-12-02 at 15 06 25](https://cloud.githubusercontent.com/assets/7525512/20836733/f0cd2e4a-b8a0-11e6-8005-c7590355abfd.png)

Apologies I can't do this myself. I hope this helps you. Also use [impallari/testing](http://www.impallari.com/testing/). The site caches fonts with the same name so to compare old and new fonts, you need to open the site again in a new tab/window.

Kind regards and have a nice weekend,
Marc

**Comment by DelveFonts** [comment]
Thanks for bringing this to our attention and for the recommends @m4rc1e. We thought the issue was resolved but will give it another shot right away.

**Comment by DelveFonts** [comment]
Fixed. After reviewing the options, we are going with your recommendation to see how that shakes out.
