### ISSUE TITLE
Ligatures for Overpass Mono?

### ISSUE THREAD

**Issue by mcepl** [RedHatBrand/Overpass#38]
I wondered there is any hope Overpass Mono would ever get programming ligatures like what Fira Code (https://github.com/tonsky/FiraCode/) has.

**Comment by DelveFonts** [comment]
We want Overpass Mono to be a great tool for programmers so we will look at the possibility of adding ligatures.

**Comment by DelveFonts** [comment]
Also, meant to say: Thank you @mcepl for bringing that up.

**Comment by mcepl** [comment]
So, why is this ticket closed?

**Comment by andyfitz** [comment]
It's not on the immediate roadmap and hasn't been a release goal.   I wouldn't consider it an issue.

using Fira code with ligatures got annoying for my tastes.  

Will keep assessing demand for future versions

**Comment by mcepl** [comment]
Thank you for clear stance.
