### ISSUE TITLE
A few minor nits

### ISSUE THREAD

**Issue by spotrh** [RedHatBrand/overpass#4]
Thanks for the new fonts. That said, a few minor nits that if resolved, would make my life simpler.

1) Instead of a zip file checked into git, can you do a proper release of the ttf through github?
2) And as part of that release, can you use a sane incrementing version? The old sources were marked as 1.01, the font metadata in these releases shows "1.000". Maybe bump to 1.1 with the next change?

**Comment by andyfitz** [comment]
Done!

**Comment by andyfitz** [comment]
minor release done .. the standard has been established ;-)
