### ISSUE TITLE
Not on Google Fonts

### ISSUE THREAD

**Issue by WolfEdge** [RedHatBrand/Overpass#44]
On http://overpassfont.org/ it references Google Fonts as one of the hosts that can be used to get the font at the bottom of the page. Clicking on the Google Fonts link shows Overpass is not there.

I've searched the Google Fonts directory myself and I can't find it. It seems to have been removed, which is a shame really.

Apologies if this is not a good place to put this. I was not sure who to contact.

**Comment by roberrrt-s** [comment]
google/fonts#128

**Comment by andyfitz** [comment]
https://fonts.google.com/?query=overpass  

![Party Time](http://media1.giphy.com/media/CkkVulYzFjd72/giphy.gif)

**Comment by jkbrock** [comment]
Congrats font team!!!! Great work!!

**Comment by WolfEdge** [comment]
Ta. Congrats guys! And thank you for updating my issue @andyfitz. Just wanted to say Overpass Mono looks _amazing_ in my terminal.

**Comment by roberrrt-s** [comment]
Much love <3
