### ISSUE TITLE
Mono: Parens and braces are difficult to distinguish at small sizes

### ISSUE THREAD

**Issue by codeman38** [RedHatBrand/Overpass#46]
In Overpass Mono, the curly brace glyphs have an extremely rounded curve, and the 'pinch' of the curve is very subtle. Because of this, they're very difficult to distinguish from parentheses at a glance, especially at smaller font sizes.

See, for instance, this comparison (9pt, 120dpi) between Overpass and three other popular open-source monospace fonts, and note how the middle of the curve is much more pointed in the other fonts:

![paren-brace-comparison](https://cloud.githubusercontent.com/assets/386563/21856256/5852de6c-d7ef-11e6-92d9-a981551a4b94.png)

[edit: updated with correct font size/DPI used for the sample]

**Comment by andyfitz** [comment]
They look very distinct to me...  more so on my system also
![eg](https://cloud.githubusercontent.com/assets/1276715/21870454/24b7c504-d8a8-11e6-9415-9848554fb0d6.png)

**Comment by davelab6** [comment]
Sometimes this is resolved by having the curly braces a little taller

**Comment by andyfitz** [comment]
yeah I had considered that but I like the vertical parity and think Dave and Delve did too.  will resolve as a #wontfix
