### ISSUE TITLE
Hinting could be improved with ttfautohint

### ISSUE THREAD

**Issue by codeman38** [RedHatBrand/overpass#5]
The hinting in the current release of the fonts is rather ugly on systems where bytecode hinting is enabled (e.g., Freetype 2.4+ with fontconfig set to 'medium' or 'full' hint style). This is especially noticeable in the Italic styles-- note the ridiculously inconsistent line widths in the screencap below:

![overpass-bad-hinting](https://cloud.githubusercontent.com/assets/386563/9499387/3a06af90-4bed-11e5-95b3-1e3c2a7f0c9e.png)

For comparison, here's what the font looks like after running `ttfautohint` on it:

![overpass-italic-autohint](https://cloud.githubusercontent.com/assets/386563/9499337/f45fc31e-4bec-11e5-93ab-13f82c357567.png)

**Comment by DelveFonts** [comment]
Hey Andy,

I was excited to see the new fonts posted on github. Very cool.

As you may have noticed, there have been a few issues with the fonts 
that were brought up by followers in the last couple days. I am happy to 
fix them, if it is ok by you.

And are you ok with me responding to issues on your github Overpass 
repository? I don't want to overstep any bounds and I certainly don't 
presume to speak for Red Hat.

Regards,
Delve

P.S. That first issue concerning the ttf outlines not being available 
for the Light and the accent placement can be closed now.




codeman38 wrote:

**Comment by DelveFonts** [comment]
Yikes! Yes, there is definitely room for improvement there. Thank you for bringing this to our attention codeman38.

**Comment by andyfitz** [comment]
eww, this is why I leave freetype hinting off on all my Fedora machines.  
It's a scary dark art.
But thanks for the insight @codeman38   I forgot how awesome TTF autohint is nowadays.

@DelveFonts are we  happy to accept any change that has TTF autohint run on it?

**Comment by DelveFonts** [comment]
@andyfitz Yes, any but the Regular and Bold. Those two have hand-edited hints applied.

**Comment by davelab6** [comment]
@DelveFonts have you checked out the ttfautohint 'overrides' feature? Jasper de Waarde posted a video in http://typedrawers.com/discussion/1143/how-to-use-ttfautohint

**Comment by andyfitz** [comment]
This has been done thanks @jimmac
