### ISSUE TITLE
Obliques named as Italic, and Italics missing

### ISSUE THREAD

**Issue by nitrofurano** [RedHatBrand/overpass#8]
hi Andy!
nice typeface family, but there is a mistake: obliques are wrongly named as italic, and italics are missing...
cheers,
p.

**Comment by DelveFonts** [comment]
Hi nitrofurano, Thank you for bringing this up. The italics for Overpass were actually carefully drawn to yield the highest fidelity and remain visually consistent with the upright fonts — a much harder task than simply slanting the glyphs or making them oblique. Applying a slant to the upright forms will not result in the refined letter shapes of the italics provided in the Overpass family. Doing so, the weight gets distributed unevenly along axis and shapes get distorted. We worked diligently to avoid that effect. Also, being that this is a 20th century design we are adapting for use in the digital realm of the 21st century, we did intentionally choose to not change any of the letters to the more historical italic forms. The idea was to keep it contemporary and forward facing. Using the style name 'italic' is a practical matter and a common means in type design to facilitate the fonts' use in modern software. I hope my long-winded explanation brings some insight to why the italics are the way they are.
