### ISSUE TITLE
overpassfont.org does not allow users to increase font size

### ISSUE THREAD

**Issue by joeframbach** [RedHatBrand/overpass#9]
Steps to reproduce:
1. Open overpassfont.org
2. Increase font size using browser controls.

Expected outcome:
Font size increases.

Actual outcome:
Font size does not increase.

**Comment by andyfitz** [comment]
Hey thanks for the tip,  I'm about to update the site once we get Overpass hosted on our official CDN.  I'll be sure to fix this.

I'm using viewport units to size the text (which was a lazy way of making the site mobile friendly without setting rules at break points )   

I'll be sure to use a different technique on the update 

Andy

**Comment by andyfitz** [comment]
Heres a prototype for the next gh-pages site 
http://codepen.io/andyfitz/live/GoWmyW?editors=110

still to fix up the specimens but it does allow for manual resizing.

**Comment by andyfitz** [comment]
went ahead and changed it.. still need to give this project a proper site
